[managers]
manager ansible_host=10.146.100.134 ansible_user=ubuntu

[workers]
worker1 ansible_host=10.146.100.119 ansible_user=ubuntu
worker2 ansible_host=10.146.100.179 ansible_user=ubuntu

[swarm:children]
managers
workers

[swarm:vars]
ansible_ssh_private_key_file=./multipass-ansible
